### ISSUE TITLE
Turn like play order within a stage?

### ISSUE THREAD

**Issue by pardahlman** [boardgameio/boardgame.io#1017]
In my game, the main portion is played concurrently by all players. This is achieved by setting `all` players in the main `stage` where they can carry out their moves. When a turn is coming to an end, bonus moves (defined in a bonus `stage`) can be made once per turn for eligible player. These actions should be carried out in sequence with the player closes to the `currentPlayer` going first.

Is it possible to get a turn like play order for the bonus stage? I know this can be solved by using phases and turns, but conceptually it all happens within a turn so it would be fitting to model it as such.

**Comment by delucis** [comment]
You can use the `next` option to `setActivePlayers` to queue up a sequence of stage configurations:

```js
setActivePlayers({
  value: { '0': 'bonus' },
  next: {
    value: { '1': 'bonus' },
    next: {
      // etc.
    },
  },
});
```

So in this example, when player `0` ends their stage, active players will move on to the `next` value, placing player `1` in the `bonus` stage and so on.

This nested `next` syntax should work, but it’s not super nice to generate dynamically, so changing it is [on the to-do list](https://github.com/boardgameio/boardgame.io/projects/7#card-63028311). The idea would be to support an array of arguments to queue up future values, which would be much cleaner to work with, e.g.

```js
setActivePlayers([
  { value: { '0': 'bonus' } },
  { value: { '1': 'bonus' } },
]);
```
