### ISSUE TITLE
Missing playerID in ctx onMove callback

### ISSUE THREAD

**Issue by pardahlman** [boardgameio/boardgame.io#1018]
The `ctx` that is passed to a move contains `playerID`, which is useful when updating G or evaluating if the move is valid etc. The `ctx` provided to `onMove` callback lacks this property. I find that I sometime want to evaluate if a move should cause a stage transition for the player who made that move. Hence my question: what are the thought behind not having `playerID` for the `ctx` argument in `onMove`? Does it sound like a good idea to add support for this? If not, are there any other recommended ways of achieving this? At the moment, I do this check within multiple moves which feels sub-optimal.

(_Game context: all players are active in the `play` stage. they should no longer be active if they do not have any chips left, their board has "exploded" and possibly other future conditions_)

**Comment by delucis** [comment]
I think including `ctx.playerID` in `onMove` would make sense. The reason it isn’t included currently is because none of the hooks receive `playerID`. It can be a slightly confusing value for the other hooks — especially the `onBegin` hooks where `playerID` is the player who made the last action where many might assume it would be the player whose turn is beginning.

Adding it to `onMove` would be a good idea, I’d say.

**Comment by delucis** [comment]
Right. The `onMove` call here needs to receive `playerID`:

https://github.com/boardgameio/boardgame.io/blob/d4cb2c19b7176117ee871edee9717a9afcc600cb/src/core/flow.ts?rgh-link-date=2021-10-16T17%3A39%3A09Z#L730

I’m not sure if it’s safe to add `playerID` directly to that `state` variable you linked to as that might result in `playerID` getting persisted (maybe?), but perhaps something like this would work:


```js
    const G = phaseConfig.turn.wrapped.onMove({
      ...state,
      ctx: { ...state.ctx, playerID }
    });
```

**Comment by delucis** [comment]
For testing, I’d suggest turning [this block in `flow.test.ts`](https://github.com/boardgameio/boardgame.io/blob/d4cb2c19b7176117ee871edee9717a9afcc600cb/src/core/flow.test.ts#L220-L242) into a `describe` block and adding a separate test where you do something like `onMove: (G, ctx) => ({ hasPlayerID: !!ctx.playerID })` and then test that `G.hasPlayerID` is `true`.
