### ISSUE TITLE
React Native: ctx and G undefined under some conditions

### ISSUE THREAD

**Issue by kuket15** [boardgameio/boardgame.io#1024]
On React Native it looks like **ctx, G and other props** are undefined when **multiplayer** parameter is set in the **Client** constructor.

I'm temporarily fixing the component rendering using something like:

`return !!ctx && <View>...</View>`

but I can't use plugin libraries like [bgio-effects](https://github.com/delucis/bgio-effects). In this case the **EffectsProvider** tries to use the prop **plugins** without proper validation (**boardProps.plugins.effects**) and detonates.

[Here](https://codesandbox.io/s/icy-sea-wo2pj?file=/src/App.tsx) a minimal sandbox showing the problem. I'm pretty sure **setup()** is called only after the first component rendering.

Am I doing something wrong or is this supposed to be a bug? I've seen very little examples for React Native.
With React everything is working as expected.

Thanks,
Luca

**Comment by delucis** [comment]
I think the React Native client lacks a loading state. With multiplayer, the state is undefined until it's received from the server. In the React DOM client there's a (customisable) loading component that is displayed until the client receives state, so we should probably add something similar for React Native.
