### ISSUE TITLE
setActivePlayers event with array of player IDs not valid when using Typescript

### ISSUE THREAD

**Issue by walkerkd** [boardgameio/boardgame.io#1041]
The documentation for [Stages](https://boardgame.io/documentation/#/stages) has the following statement:

>    There is also a convenient syntax to enumerate the players that you want in the set of active players:
>
> ```
>    // Players 0 and 3 are added to the set of active players,
>    // and neither is placed in a stage.
>    setActivePlayers(['0', '3']);
> ```

However it appears that this is not accepted as valid when using Typescript.

**Comment by delucis** [comment]
Good catch!
