### ISSUE TITLE
Lobby server allows matches with invalid player counts to be created

### ISSUE THREAD

**Issue by RevolutionTech** [boardgameio/boardgame.io#1055]
When assigning the `minPlayers` and `maxPlayers` properties of the game object, this can influence the player counts a user can select when creating a new match in the lobby. However, these bounds do not appear to be enforced by the lobby server.

For example, the following request will succeed in creating a match of `tic-tac-toe` running on `localhost` with the property `maxPlayers` set to `2`:
```shell
$ curl -X POST -d '{"numPlayers": 99}' -H 'Content-Type: application/json' http://localhost:8000/games/tic-tac-toe/create
{"matchID":"D0aRfNrEMLa"}%  
```

**Comment by delucis** [comment]
Agreed this would be good to fix by adding some logic to the relevant endpoints in https://github.com/boardgameio/boardgame.io/blob/main/src/server/api.ts

**Comment by RevolutionTech** [comment]
Thanks @delucis! I will try to take a stab at this sometime in the next few weeks.
