### ISSUE TITLE
Type mismatch, PlayerID being optional within LongFormMove and Move types.

### ISSUE THREAD

**Issue by YoavHortman** [boardgameio/boardgame.io#1094]
If it is never possible for `LongFormMove` or `Move` functions to be called with an `undefined` `PlayerID`, does it make sense to reflect that in the types?

This issue comes up when using the flag `"strictNullChecks": true` in `tsconfig.json`

**Comment by vdfdev** [comment]
That's a good point, the library was initially developed without types and this might be some legacy code. Feel free to open a PR to fix this.

**Comment by vdfdev** [comment]
I'm not sure

**Comment by nsaritzky** [comment]
Looking at the code [here](https://github.com/boardgameio/boardgame.io/blob/3c9b9de97b72f3fa2d629524699d44cad9e8e405/src/types.ts#L203), I think so. It has

``` typescript
export type MoveFn<
  G extends any = any,
  PluginAPIs extends Record<string, unknown> = Record<string, unknown>
> = (
  context: FnContext<G, PluginAPIs> & { playerID: PlayerID },
  ...args: any[]
) => void | G | typeof INVALID_MOVE;
```
