### ISSUE TITLE
Can't get player plugin to work

### ISSUE THREAD

**Issue by mateomurphy** [boardgameio/boardgame.io#1114]
I'm following the documentation and set up a simple test like this:

```
import { PluginPlayer } from 'boardgame.io/plugins';
import { Client } from "boardgame.io/react";

const playerSetup = (playerID: string) => ({ id: playerID});
const playerView = (players: any, playerID: any) => ({
  [playerID]: players[playerID],
});

const game = {
  plugins: [
    PluginPlayer({
      setup: playerSetup,
      playerView: playerView,
    }),
  ],
};

const Board = ({ctx}: any) => {
  console.log(ctx.player)

  return null
}

const PlayerTest = Client({
  game,
  numPlayers: 2,
  board: Board,
});


export default PlayerTest;
```

From what I can tell this should work, but `ctx.player` is undefined. Am I missing something, or is there a bug?

**Comment by mateomurphy** [comment]
Ok, after reading #594, I think I've figured out that `ctx.player` isn't supposed to be available from the board, and that if I need that data from within the board it can be found at `props.plugins.player.data`, correct?

**Comment by delucis** [comment]
Hi @mateomurphy, yes that's correct — the `ctx.player` API is only available inside moves etc. and you access its state as `props.plugins.player.data`.

I'll close this as resolved, but feel free to ask any more questions if you have them!

**Comment by mateomurphy** [comment]
Thanks for the help, after playing around with plugins some more, I'm finding that it would be really useful to be able to expose an API that's available in the board. Would there be any interest in adding this? I can work on an implementation.
