### ISSUE TITLE
Update plugin documentation for `GameMethod`

### ISSUE THREAD

**Issue by kevinddchen** [boardgameio/boardgame.io#1132]
The [documentation for plugins](https://boardgame.io/documentation/#/plugins) does not include the `GameMethod` enum usage introduced in #980. 

I think it would be useful to include, since I personally spent a very long time figuring out 
    1. why `fnWrap` was being run a second time after each move
    2. why `G` was read-only inside `fnWrap` on this second call
It wasn't until I stumbled across this PR that I could reliably figure out when my moves were actually being called.

**Comment by delucis** [comment]
Sounds like a good idea. Would you be interested in submitting a PR based on your recent experience?

**Comment by kevinddchen** [comment]
Sure! More than happy to. Ill write something, and hopefully there will be some signal in the noise I write 😆
