### ISSUE TITLE
Error when set custom playerID for multiplayer local

### ISSUE THREAD

**Issue by huynhthuan** [boardgameio/boardgame.io#1141]
I create game multiplayer with local, and set playerID custom.
When i play move game show error like image below. But when i set playerID list to ['0', '1'] , game will run.
How i can fix this

Project reproduce error:  https://codesandbox.io/s/bgio-plain-js-multiplayer-forked-2e72go?file=/src/App.js

![image](https://user-images.githubusercontent.com/43500546/229744185-633e74f3-e596-4062-b79f-caab95cf09ee.png)

**Comment by rjulian** [comment]
This is due to the default playOrder being set to ['0', '1'] [here](https://github.com/boardgameio/boardgame.io/blob/main/src/core/turn-order.ts#L259). 

To override that default turn order, you'd need to set this in your Game: 
```
turn: {
    order: {
      first: ({ G, ctx }) => 0,
      next: ({ G, ctx }) => (ctx.playOrderPos + 1) % ctx.numPlayers,
      playOrder: ({ G, ctx }) => ['12','213'],    
    },
    moveLimit: 1,
    
  }
```

**Comment by huynhthuan** [comment]
> This is due to the default playOrder being set to ['0', '1'] [here](https://github.com/boardgameio/boardgame.io/blob/main/src/core/turn-order.ts#L259).
> 
> To override that default turn order, you'd need to set this in your Game:
> 
> ```
> turn: {
>     order: {
>       first: ({ G, ctx }) => 0,
>       next: ({ G, ctx }) => (ctx.playOrderPos + 1) % ctx.numPlayers,
>       playOrder: ({ G, ctx }) => ['12','213'],    
>     },
>     moveLimit: 1,
>     
>   }
> ```

Ohh ! Thanks you, my error has resolved 👍
