### ISSUE TITLE
Whats the state of the project?

### ISSUE THREAD

**Issue by on3iro** [boardgameio/boardgame.io#1150]
Hey folks,

I noticed that there has been barely any activity here for quite some time and also libraries like bgio effects seem to be more or less unmaintained at that point (cc @delucis ). Apparently the gitter chat is down as well.

Therefore I wanted to ask, what the current status of the project is and if there are any plans to move it forward in any meaningful way?

 Maybe additional maintainers could join the project (unfortunately I don't have the time to step up right now, but maybe in the future).
 
 It would be really sad to see this project slowly fade out of existence, as it is pretty great and there also aren't really any alternatives (at least that I am aware of).
 
 **EDIT**: Ok at least the gitter seams to still exist. Only the README-links seem to be broken. However none of the maintainers have been active there fore a while, as far as I can tell

**Comment by system32uwu** [comment]
> Write simple functions that describe how the game state changes when a particular move is made. This is automatically converted into a playable game complete with online multiplayer features, all without requiring you to write a single line of networking or storage code.

That's the mission of this framework, as far as I can tell it works well enough and gets the job done, if there's something that's not working for you can just open an issue on that

**Comment by on3iro** [comment]
@system32uwu sorry I am not quite sure what you are saying? I know what this project is for and I know that I could technically open issues/PRs, but there are quite a few of these and there has been no maintainer activity for a few months. For example I opened a PR inside bgio-effects in February which hasn't had any reaction by the maintainer as of yet.

**Comment by system32uwu** [comment]
Why not fork it and just use your fork with these new features then? It's not like bringing this up will bring the maintainers back, they have lives outside of open source, if you know people who'd be interested in taking on the project you can make it your own together, it's MIT at the end of the day. Many people have done this and continue to do so, that's the foss life cycle

https://www.fastruby.io/blog/open-source/guide-for-unmaintained-open-source-projects.html#start-your-own-fork

> Assuming you didn’t skip any steps, you may want to post a comment in the issue you submitted initially. In there you can say that until the maintainers respond, you will be maintaining a fork of this project.

https://www.youtube.com/watch?v=8ijzefV-B7U

https://opensource.guide/finding-users/
https://opensource.guide/building-community/

It's better to go this way, posting these kind of issues make it sound like these people owe you or anyone else something (regardless of your actual intention with opening this issue). What I found helped keep core maintainers active is [opencollective](https://opencollective.com/opensource), which you can set up quite easily.

I believe that if the maintainers see movement in your fork they'll be inspired to come back and keep adding features to the project, but well, at the end of the day there's no one paying them for their time in these projects.

**Comment by on3iro** [comment]
@system32uwu I agree with you in general, but I think it is more polite to ask maintainers about their intentions before just starting a fork and calling it a day. I am absolutely aware, that they don't owe me anything and also don't want to be demanding in any way. 
I also used open collective to contribute in the past :)

**Comment by nicolodavis** [comment]
@on3iro I've reached out to @delucis to see what his thoughts are.

As the original creator of this project, I'd love to see development continue even though I don't have time to actively contribute at the moment.

A fork makes sense if a new contributor would like to take the project in an entirely new direction (or if they're receiving sufficient resistance to contribute from existing maintainers). You'll find no such resistance from either me or @delucis.

If someone is able to take on active development, I would definitely consider adding them as a maintainer. Until then, perhaps it makes sense to mark the project as being in "maintenance mode" or something like that so that the community has appropriate expectations that active development is not happening at the moment.

**Comment by on3iro** [comment]
@nicolodavis thanks a lot for chiming in! I would love to help out, but unfortunately I barely have any time myself right now. Marking the project as currently being in "maintenance mode" is probably a good step to manage expectations for now. :+1:

**Comment by nicolodavis** [comment]
OK, I've done that. Hopefully development picks up again sometime in the future!
