### ISSUE TITLE
AI Bot for Actual Gameplay

### ISSUE THREAD

**Issue by ruichen199801** [boardgameio/boardgame.io#1163]
Hi I am new to the framework, and I wonder if this framework is still under active development? 

To be more specific, I am currently building a single player card game, and I want to employ the AI as the opponent for the real player to play against. I found the AI bot used for simulation worked quite well for my project. 

However, I am curious about when the detailed documentation on AI bot will come out, and if the support for "adding bots to games as opposed to simulating moves" will ever be added? 

Thanks!

**Comment by nicolodavis** [comment]
The project is not being actively developed at the moment (see #1150).

About adding bots to games rather than simulations, I'd definitely be willing to review a PR if you'd like to work on this.

Here are some thoughts:

1. There is the mechanical aspect of actually getting the bot to make a move during game play (which does not exist today).
2. Improving the quality of bot play. Reinforcement Learning on a linear combination of features combined with MCTS might be the way to go here.

**Comment by ruichen199801** [comment]
Thanks for the quick response! I'm just starting out on the project, and if there's no AI opponent solution available yet, I might consider manipulating opponent move on the client side (e.g. when the human player clicks the card to play it, an event handler in the Board component will invoke the PlayCard move for the AI player after the player turn ends, which could be as simple as picking a card randomly).

**Comment by nicolodavis** [comment]
That's a good way to implement it as well.

**Comment by nicolodavis** [comment]
Feel free to re-open this issue if you run into any problems as you're implementing the client side bot for your game.

**Comment by Toshinaki** [comment]
@ruichen199801 
Hi I'm having exactly the same question.
Have you found any solutions? Or maybe could you please share some code?

**Comment by ruichen199801** [comment]
@Toshinaki 
Hi, yes bascially you can put your AI logic into a handler function like [this](https://github.com/ruichen199801/wizard-duel/blob/v0.171/src/components/WizardDuelBoard.js#L127), and let it trigger whenever `G` or `ctx` changes like [this](https://github.com/ruichen199801/wizard-duel/blob/v0.171/src/components/WizardDuelBoard.js#L180). 

With this client-side approach, sometimes you need some workarounds when the client state is out of sync with boardgame.io's backend state (aka `G` and `ctx`). For example, I want the AI opponent to "think" for a few seconds during its turn for my card name, I had to add a timeout for that to happen. However that's not a big issue if you are not building a complex game.

You can take a look at my project in work - [Wizard Duel](https://github.com/ruichen199801/wizard-duel). Please ⭐ if you find it useful!

**Comment by Toshinaki** [comment]
@ruichen199801 
Wow, that's interesting! (Though I have to say that the enemy got too much recovery card...
And thanks for sharing, your code is very helpful.
Thank you!!
