### ISSUE TITLE
Redux actions are not sent to server when redux devtools is enabled

### ISSUE THREAD

**Issue by Toktik** [boardgameio/boardgame.io#168]
When redux devtools enhancer is enabled, the client does not send events to server because redux devtools encloses the real action into PERFORM_ACTION and boardgame.io whitelists actions here:
https://github.com/google/boardgame.io/blob/master/src/client/multiplayer/multiplayer.js#L59

**Comment by nicolodavis** [comment]
This should be fixed in `0.20.3`.

**Comment by Toktik** [comment]
Thanks for a quick fix! However, still the server will not work, because all redux actions are sent encapsulated inside PERFORM_ACTION and server does not know how to handle.

**Comment by iamchristopher** [comment]
@nicolodavis This is still an issue with `0.22.1`.

**Comment by delucis** [comment]
Closing this as stale — feel free to reopen if someone has a recent example of this bug.
