### ISSUE TITLE
UI framework

### ISSUE THREAD

**Issue by nicolodavis** [boardgameio/boardgame.io#282]
Just recording the current state and future work planned.

We're going to ship both 2D and 3D (using threejs) components!  The two sets of components will be created using the same API so you can seamlessly switch between the two.

I've started a new branch `3d` to track development of this. I've split the UI framework into 2d and 3d directories:

```
src/ui/
├── 2d
│   ├── card.css
│   ├── card.js
│   ├── card.test.js
│   ├── deck.css
│   ├── deck.js
│   ├── deck.test.js
│   ├── grid.js
│   ├── grid.test.js
│   ├── hex.js
│   ├── hex.test.js
│   ├── logo.js
│   ├── logo.test.js
│   ├── token.js
│   ├── token.test.js
│   ├── ui.js
│   ├── ui.ssr.test.js
│   └── ui.test.js
├── 3d
│   ├── card.css
│   ├── card.js
│   ├── deck.css
│   ├── deck.js
│   ├── grid.js
│   ├── hex.js
│   ├── token.js
│   └── ui.js
├── card.js
├── deck.js
├── grid.js
├── hex.js
├── hex-utils.js
├── hex-utils.test.js
├── token.js
├── ui-context.js
└── ui.js
```

Each component has a file in the root directory (which is exposed as the public API) and one in each of the 2d and 3d directories.  The root component just delegates to the appropriate rendering component based on a prop that you pass to the `<UI>` element.

For example:

```
<UI>
  <Deck><Card/></Deck>
</UI>
```

renders DOM elements as cards and decks, whereas:

```
<UI three={true}>
  <Deck><Card/></Deck>
</UI>
```

renders to a threejs canvas.

Things missing in the 3D component set:
- [ ] hex grids
- [ ] grids
- [ ] tokens

Things missing in the 2D component set:
- [ ] ability to drag / drop tokens (currently only implemented for cards / decks)

**Comment by nicolodavis** [comment]
Let's keep it as a separate branch for now and work on that. I'll merge it in once the 3D components have feature parity with the 2D components.

**Comment by Korla** [comment]
Alright, I'll start working on it on that branch on my fork, and will make PR(s) to your branch as necessary.

**Comment by flamecoals** [comment]
FYI, I am working now on the "ability to drag / drop tokens (currently only implemented for cards / decks)" for the 2D component

**Comment by harviu** [comment]
Is anyone doing the grid, hex map or tokens right now? I am interested in doing them.

**Comment by nicolodavis** [comment]
Are you talking about the 3D components?  I think @Korla signed up for them but probably got busy.

**Comment by nicolodavis** [comment]
I'm going to merge the 3D branch into master after https://github.com/nicolodavis/boardgame.io/pull/316 so just be aware of that.  It probably won't change any of the directory structure, but just the destination of your pull request once you're done with your change.

About camera views, we should probably have a pan mode. The threejs repo has some examples of this I think, but I haven't had time to explore them yet.

**Comment by nicolodavis** [comment]
I'm almost ready to merge the `3d` branch into `master`.  The one remaining item is that `token.js` does not have 100% test coverage.

@flamecoals I think this was from your PR #316?

![screenshot from 2019-01-21 23-17-22](https://user-images.githubusercontent.com/236078/51483073-222a1900-1dd3-11e9-9030-95661aa25eb6.png)

**Comment by nicolodavis** [comment]
Merged into `master`.

**Comment by nicolodavis** [comment]
FYI: Might be worth checking out https://github.com/drcmda/react-three-fiber for the 3D stuff.

**Comment by harviu** [comment]
This is interesting, I'll have a look

**Comment by gabrielecastellano** [comment]
Hi everyone,
Is this framework documented anywhere? Are there available examples?

Thanks

**Comment by delucis** [comment]
We removed it because we didn’t have the time to maintain it and wanted to focus on the core engine. You can find the old components here: https://github.com/nicolodavis/bgio-react-component-toolkit
