### ISSUE TITLE
Problems with TicTacToe tutorial

### ISSUE THREAD

**Issue by seoanezonjic** [boardgameio/boardgame.io#571]
Hey folks
I´ve found your boardgame.io project and I think that it's very interesting. I've decided to give it a try so I began for the TicTacToe tutorial. My aim is to perform the full process of the app building with React until deploy de app in Heroku. In this way, I can test and understand your project and finally, check if it cover my needs. In this process I've found several issues:

1. I began with this tutorial: https://boardgame.io/documentation/#/tutorial and I've found some problems that I fixed analysing the code in the examples folder: https://github.com/nicolodavis/boardgame.io/tree/master/examples/react-web/src/tic-tac-toe. But the two sources are different versions that I think that it should be the same.
2. The tutorial, in the multiplayer description makes a "jump" in which the code is split in the _game_ and _board_ files and this step is not explained. I suppose that fluent React developers can make this transformation easily, but people that are not familiarized with this platform, as me, find this step difficult. When I put together all the code, the multiplayer system Local Master works in my computer, but the Remote Master system not.
3. As Local Master failed to me, I realized that the tutorial has the following link to a working example of the system: https://codesandbox.io/s/boardgameio-fsl8y. I downloaded it and it worked perfectly. This version is also different to the tutorial and the example TicTacToe codes.
4. I've build a github repo and connect it to a heroku account to perform the deploy. After the deployment process, in Mozilla I was the following error when I choose a player:
` Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/socket.io/?EIO=3&transport=polling&t=N42v9Ah. (Reason: CORS request did not succeed)`
Searching in google, I've changed:
`multiplayer: SocketIO({ server: "localhost:8000" })`
to
`multiplayer: SocketIO({ server: "https://boardgameparty.herokuapp.com/:8000" })`
But now, Mozilla don´t show any error only the "Connecting..." message but in Chrome appears the following error:
`polling-xhr.js:271 POST https://boardgameparty.herokuapp.com/socket.io/?EIO=3&transport=polling&t=N43J2-R 404 (Not Found)`

Currently, I don't know how to fix this problem. I think that an update of the tutorial covering from the app building until the deployment process in a server (not necessarily in heroku ) would be very interesting.
Thank you in advance
Pedro Seoane

**Comment by nicolodavis** [comment]
This is great feedback.   Thank you!

Yes, I think the CodeSandbox link sometimes falls out of sync with the tutorial code.  We'll have to come up with a better process for this.  I think I might consider having CodeSandbox pull from the Git repo directly and making sure that the tutorial uses the same code.

About deployment, that is on the radar.  You should see a guide on how to deploy it on various options prior to our v1 launch.

**Comment by delucis** [comment]
Closing this as I think this has mostly now been addressed. The tutorial was rewritten in #714, addressing the “jump” described in 2 above, and I think resolving 1 too. [A Heroku deployment guide](https://boardgame.io/documentation/#/deployment?id=heroku) has also since been added to the docs. Thanks for the helpful feedback!
