### ISSUE TITLE
 localStorage as Local storage.

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#679]
What do you think about idea to allow localStorage to be storage for localMaster? Sometimes it could be useful to be able to back to same game after accidental tab close or refresh without need of server in backend.

**Comment by delucis** [comment]
This should be possible. The main work would be writing a local storage implementation of the storage API. You can find [the synchronous base class here](https://github.com/nicolodavis/boardgame.io/blob/b2d6b067d6d737406484a648b6697c8d1443570e/src/server/db/base.ts#L113-L165). The same principle would work for other browser storage approaches.

Then the local transport would need to be updated to receive an optional storage instance — it currently creates its own instance of the `InMemory` implementation internally:

https://github.com/nicolodavis/boardgame.io/blob/b2d6b067d6d737406484a648b6697c8d1443570e/src/client/transport/local.js#L69

But the changes to pass in a storage option would be minimal.

Usage might be something like:

```js
import { Client } from 'boardgame.io/react';
import { Local } from 'boardgame.io/multiplayer';
import { LocalStorage } from 'bgio-localstorage';

const client = Client({
  multiplayer: Local({
    db: new LocalStorage(),
  }),
});
```

There probably won’t be capacity on our end to write a local storage adapter ourselves in the near future, but I’m happy to help if you have any questions.

**Comment by pociej** [comment]
Yeah i already checked current implementation and i think i see how it should be implemented. Just wanted to know if you prefer it to be part of think package or separate repo, but from what i see above you prefer to have it outside as all other storage implementations. Will let you know soon.

**Comment by nicolodavis** [comment]
If it's a very simple implementation that just hydrates the in-memory store on page load and then persists it in localstorage when an action is made, we could also just extend the current `Local` implementation to accept a `persist: true` option that does this behind the scenes without creating a new storage adapter.

**Comment by pociej** [comment]
ok @nicolodavis @delucis i have this created as separated storage so it wont be big job change conception and make it part of main repo.Tomorrow will make PR.

**Comment by HydraOrc** [comment]
Is this feature ready yet? Would be nice to have in my project

**Comment by pociej** [comment]
oh Great Scott! i just see i didnt fix something and my PR i still not merged @HydraOrc  @nicolodavis  i will apply what was request to PR this weekend and we will merge it.

**Comment by pociej** [comment]
@HydraOrc  https://github.com/boardgameio/boardgame.io/pull/691 i just pushed some commits there, waiting for @nicolodavis acceptance.
