### ISSUE TITLE
Use deltas instead of whole game transfer for network multiplayer

### ISSUE THREAD

**Issue by HydraOrc** [boardgameio/boardgame.io#757]
Right now I have lots of information in my game, like what map tiles and what units are visible right now for a certain player, plus the game could update quite frequently, so it is way too heavy to transfer the whole state

**Comment by delucis** [comment]
Open to a PR if there’s a performant way to calculate the deltas and a reliable way for clients to receive the relevant patch without data loss. Moves use Immer to mutate state, which provides a [patch implementation](https://immerjs.github.io/immer/docs/patches), but we’d still need to find a way to combine that with mutations outside of moves and then apply the patch on the client.

Please also bear in mind that update payloads from the server will be Gzipped and — assuming game state serializes to a pretty repetitive string — the transferred data is usually significantly less than the raw size (>50% less in my experience), so testing the actual performance benefits of moving to a patch model would be important.

**Comment by nicolodavis** [comment]
The mail reason we use full state updates instead of just transmitting the actions and letting each client update itself is because of secret state (which prevents each client from being able to properly update itself due to lack of the full state).

One possibility (that doesn't involve patches) might be to allow this delta mode when no secret state is involved.

**Comment by HydraOrc** [comment]
I mean you can calculate differences for each player server-side, including the secret state, and then just pass differences to each client and apply patches like in https://www.npmjs.com/package/rfc6902 library, it should work just fine and reduce the amount of data transfered

**Comment by pastpatryk** [comment]
#920 is merged already, so this can be closed now
