### ISSUE TITLE
Improve consistency around “match” vs “game”

### ISSUE THREAD

**Issue by delucis** [boardgameio/boardgame.io#763]
There is still some work needed to make the framework fully consistent around using the term “match” to describe an instance of a specific game (see #709). Should we aim to get this done as part of 0.40.0?

- [x] Database connectors (would require updating the various third-party connectors):

  - [x] `createGame` method should be renamed `createMatch`

  - [x] `listGames` method should be renamed `listMatches`

  Done in #806

- [x] `gameID` → `matchID`

  - [x] in React client

  - [x] in plain JS client

  - [x] in debug panel

  - [x] in master

  - [x] in server transport (cosmetic argument renaming)

- [x] `gameMetadata` → `matchMetadata`

  - [x] in React client

  - [x] in plain JS client

  (This had in fact been done in #704, because the 0.40.0 docs have been updated to show `matchMetadata`, but I think I may have overwritten those changes when merging in the Typescript clients.)

- [x] `updateGameID` → `updateMatchID` (plain JS client)

There may be some more I’ve missed, but I think that’s most of it.

**Comment by evandroabukamel** [comment]
Hey, @delucis , I'm working on that if you don't mind. I'm opening a PR.
