### ISSUE TITLE
Debug panel keyboard shortcuts for selecting among activePlayers and end turn/end phase/end stage

### ISSUE THREAD

**Issue by shenker** [boardgameio/boardgame.io#771]
1) As far as I can tell, the debug panel cannot issue moves for activePlayers other than currentPlayer (even though it seems like you should be able to click on the numbered boxes under “Players” to select other players). It would be nice to have this capability, and also to have keyboard shortcuts to select amongst these activePlayers.

2) It would be great to have keyboard shortcuts for end turn/end phase/end stage. The debug panel has been super helpful for learning bgio, and keyboard shortcuts would make experience even more efficient.

**Comment by nicolodavis** [comment]
Good idea!

**Comment by delucis** [comment]
For some context re: 2, if someone would like to pick this up, this is where the event buttons in the debug panel are currently declared:

https://github.com/boardgameio/boardgame.io/blob/d8948d32c87e3161c875bdedb59be7da23d67c78/src/client/debug/main/Main.svelte#L95-L105

We are [already reserving a keyboard shortcut for the events](https://github.com/boardgameio/boardgame.io/blob/d8948d32c87e3161c875bdedb59be7da23d67c78/src/client/debug/utils/shortcuts.js#L9), so we should be able to wire them up without too many complications. We could potentially use the `<Move>` component to render them as interactive functions like the moves are, or alternatively the `<Hotkey>` component to render them like the reset/save/restore controls.

`<Move>` component in use:

https://github.com/boardgameio/boardgame.io/blob/d8948d32c87e3161c875bdedb59be7da23d67c78/src/client/debug/main/Main.svelte#L87

`<Hotkey>` component in use:

https://github.com/boardgameio/boardgame.io/blob/d8948d32c87e3161c875bdedb59be7da23d67c78/src/client/debug/main/Controls.svelte#L42

Would also be cool to fix 1 — I’ll see if I can figure out why that’s happening.
