### ISSUE TITLE
implement react examples as hooks

### ISSUE THREAD

**Issue by jstacoder** [boardgameio/boardgame.io#772]
the react examples would be much simpler as functional components, i think ill do a PR, and see if it looks good.  thoughts?

**Comment by delucis** [comment]
Thanks for taking the time to put together #773! I also personally prefer writing function components and using hooks, but I’m not sure what’s best here. [React’s own introductory tutorial](https://boardgame.io/documentation/#/stages) barely mentions function components and doesn’t mention hooks at all, so might we inadvertently be introducing confusion for less experienced React users?

**Comment by nicolodavis** [comment]
I'm also of the opinion that we should optimize for less experienced users.  Seasoned React users will know what to do to write that code using hooks.

**Comment by jstacoder** [comment]
good point, i guess i was thinking the shorter implementations would be simpler, but yes, sometimes things can be too simple.

**Comment by delucis** [comment]
Thanks for the PR in any case 🙂

**Comment by shamseen** [comment]
sorry to resurrect this. is there a place to see the functional components docs? i'm tryna convert the tic tac toe tutorial on the fly and i'm hitting errors

**Comment by jstacoder** [comment]
@shamseen https://reactjs.org/docs/hooks-intro.html

**Comment by shamseen** [comment]
@jstacoder sorry i meant the bgio docs re-written in functional components

**Comment by delucis** [comment]
@shamseen Check out the PR linked above: https://github.com/boardgameio/boardgame.io/pull/773/files

You can’t see the docs rendered out, but you can see the proposed code changes.
