### ISSUE TITLE
How to allow players to take simultaneous turns?

### ISSUE THREAD

**Issue by popey456963** [boardgameio/boardgame.io#774]
We have a game where players are dealt nine cards, and put them in an order.  After this has been done for everybody, the cards are revealed.

We would ideally like this to happen simultaneously, as all players can receive / take their turns in order, but cannot work out how to get it to happen in the engine.

This was originally suggested in https://github.com/boardgameio/boardgame.io/issues/49 but then closed.

**Comment by delucis** [comment]
I’m not sure if it fully covers your use case, but have you checked out Stages ([docs](https://boardgame.io/documentation/#/stages))? Stages allow you to have multiple active players who can make moves in any order.

**Comment by popey456963** [comment]
That works almost exactly as we want!  Except there doesn't seem an easy way to end a 'phase' when a 'stage' has ended.  Stages, unlike turns and phase don't appear to have an 'onEnd' function?

**Comment by delucis** [comment]
Right, there isn’t currently an `onEnd` for stages. (There’s a feature request in #608).

What you probably would need to do for now is to call some code from the move that ends the stage. For example, let’s say in your example each player calls an `orderCards` move which will set their card order and end their set-up stage:

```js
function orderCards(G, ctx, order) {
  // apply the card order somehow...
  // then end the player’s stage
  ctx.events.endStage();
}
```

In this move, add a check that will read `ctx.activePlayers` (a map of player IDs to stage names that boardgame.io manages), and if the player is the last active player, end the phase:

```js
function orderCards(G, ctx, order) {
  ctx.events.endStage();
  // check how many players are active and end the phase if this is the last active player
  if (Object.keys(ctx.activePlayers).length === 1) {
    ctx.events.endPhase();
  }
}
```

This check assumes you have a gradually emptying `activePlayers`, but you could also write a more complex check to read which stages each player is in etc. if necessary. `ctx.activePlayers` looks something like `{ '0': 'stage-A', '2': 'stage-B' }` or is `null` when no players are active.

See also #769 for a similar question.

**Comment by popey456963** [comment]
For future visitors, our end result for getting a single simultaneous action per phase is:

```
    phases: {
        play: {
            onBegin: (G, ctx) => {
                // give cards to everybody

                ctx.events.setActivePlayers({
                    all: Stage.NULL,
                })
            },
            moves: {
                submitOrders: (G, ctx, selected, player) => {
                    // commit player orders
                    ctx.events.endStage()

                    if (Object.keys(ctx.activePlayers).length === 1) {
                        ctx.events.endPhase();
                    }
                }
            },
            onEnd: (G, ctx) => {
                // on phase end
            },
            turn: {
                order: TurnOrder.ONCE
            },
            start: true,
            next: 'play'
        }
    }
```

**Comment by delucis** [comment]
Great! Don’t think you need the `turn` section here (as technically all the players submit their orders within one turn), so the default order should be fine.

**Comment by alexjurkiewicz** [comment]
The required logic has changed a little, you can't call the `setActivePlayers` event from within phase `onBegin`. Instead there is now support for [Configuring active players at the beginning of a turn.](https://boardgame.io/documentation/#/stages?id=configuring-active-players-at-the-beginning-of-a-turn).

```typescript
# Game config
  phases: {
    setup: {
      start: true,
      next: 'main',
      turn: {
        activePlayers: { all: Stage.NULL, minMoves: 1, maxMoves: 1 },
      },
      moves: {
        selectStartingCards,
      },
    },
    main: {
      ...

# Move config
function selectStartingCards(G: MyGame, ctx: Ctx, ...) {
  # Select starting cards
  ctx.events!.endStage();
  if (ctx.activePlayers && Object.keys(ctx.activePlayers).length === 1) {
    console.log("All players have selected their starting cards");
    ctx.events!.endPhase();
  }
}
```

**Comment by delucis** [comment]
Thanks for sharing @alexjurkiewicz!
