### ISSUE TITLE
Hide some parameters in debug menu

### ISSUE THREAD

**Issue by popey456963** [boardgameio/boardgame.io#775]
We pass some fairly large objects through the global state variable.  Some items, such as the map, contain hundreds of entries.  It would be useful to have a way to filter items seen through the debug menu.

**Comment by delucis** [comment]
There was [some discussion](https://gitter.im/boardgame-io/General?at=5ea1d77f501f8f72a5fd5678) of using something like [`svelte-json-tree`](https://github.com/tanhauhau/svelte-json-tree#svelte-json-tree) to render `G` & `ctx` in the debug panel. Would that be helpful in this case too?

**Comment by popey456963** [comment]
That would be perfect for our use case! 👍

**Comment by popey456963** [comment]
I'm working on a PR for this.

**Comment by popey456963** [comment]
On a branch that works but tests are failing: https://github.com/popey456963/boardgame.io/tree/feature/json-tree-in-debug-menu

**Comment by delucis** [comment]
One thing I think you need to do is to include `svelte-json-tree` in the list of `node_modules` that get transformed before being used by Jest here:

https://github.com/boardgameio/boardgame.io/blob/fa865dad6d548bb6296ca7d1c756cb6adc923c3c/package.json#L193

However, I also had a quick go with the plain `svelte-json-tree` package and got the build & examples working OK, but tests were producing errors despite changing that. (Producing `TypeError: JSONNode is not a constructor` errors.)

Feel free to open a work-in-progress PR so we can see the errors and try to figure things out there. Thanks for taking this on!
