### ISSUE TITLE
How to procedurally generate the game board? (so each different game has a unique board)

### ISSUE THREAD

**Issue by JohnnyWobble** [boardgameio/boardgame.io#776]
I want to create a game similar to Risk, but one of the things I want to change is a procedurally generated map. I have already written the code to do the generation, I'm just confused how I should implement it. I'm thinking the server should generate the board (it can take a minute or so), and then it sends it out to all of the clients, but I really have no clue how to implement that. Does anyone know of any projects that have implemented a similar mechanism?

**Comment by delucis** [comment]
What does the generated data look like? In general this kind of work would be handled by the game definition’s `setup` method, so you would generate the map in `setup` and store the map data in `G`, which moves & UI could then read from.

**Comment by JohnnyWobble** [comment]
Ok, that makes sense. Thanks!
