### ISSUE TITLE
Increase z-index of the debug panel

### ISSUE THREAD

**Issue by popey456963** [boardgameio/boardgame.io#778]
At the moment, elements with a high z-index can be rendered over the side debug panel.  It would be useful to increase it to some high value so that it's always on top.

**Comment by popey456963** [comment]
**Without Z-Index**

![image](https://user-images.githubusercontent.com/1338129/90426244-b09e7380-e0b8-11ea-9229-e5aea06eb6db.png)

**With Z-Index**

![image](https://user-images.githubusercontent.com/1338129/90426256-b5fbbe00-e0b8-11ea-8d92-ca87c10cac94.png)

**Comment by nicolodavis** [comment]
@popey456963 This would be a good change to get in. Would you mind whipping up a quick PR?

Love the isometric rendering BTW!

**Comment by popey456963** [comment]
> Love the isometric rendering BTW!

Thanks!  Isometric rendering was such a pain to actually implement in HTML, but it was so worthwhile. 👍 

PR created at #780
