### ISSUE TITLE
Debug panel styling of selects affects page elements

### ISSUE THREAD

**Issue by popey456963** [boardgameio/boardgame.io#782]
```
  .debug-panel :global(button, select) {
    cursor: pointer;
    outline: none;
    background: #eee;
    border: 1px solid #bbb;
    color: #555;
    padding: 3px;
    border-radius: 3px;
  }
```

It appears this CSS captures the 'button' styling to be within the debug menu but does not for the 'select' styling.  See Firefox's view of this:

![image](https://user-images.githubusercontent.com/1338129/90780270-35c29c00-e2f6-11ea-915b-79dce316f528.png)

The `button` styling only affects things within the debug panel, but `select` affects all.

**Comment by delucis** [comment]
Looks like comma-separated items inside `:global()` don’t get resolved separately, they just get preserved from being mangled by Svelte’s scoping mechanism. This should probably be:

```css
  .debug-panel :global(button), .debug-panel :global(select) {
```

Good catch!
