### ISSUE TITLE
[0.40] Match data is not reset when starting a new match

### ISSUE THREAD

**Issue by adngdb** [boardgameio/boardgame.io#789]
Here's a bug that I can reproduce on the 0.40 branch but not on the last release (0.39.16). 

When you start a new multiplayer match, everything works fine. Then the match ends, both players leave, and the same two players want to have a rematch. They thus start a new game, fresh match id and all, join and start the match. And then, damn, they end up with the data from the previous match, which is already ended, and they can't do anything at all. 

## Steps to reproduce

1. Check out this code example: https://github.com/adngdb/bgio-gameover-metadata
2. Run the server and the client
3. Connect with two clients, make one create and join a 2 players game, then make the other join too
4. Click the "Finish" button to end the game
5. Make both players leave and exit the match
6. Create a new 2 players game, have both clients join and start the game

## Actual result

The players end up with the data from their first game, which is already finished.

## Expected result

Players get fresh data and can play a new game.

## Notes

I've tried to investigate this but it's a bit difficult with my current knowledge of the framework. I suspect something goes wrong in the transport layers, either with a `matchID` not being correctly set somewhere, or data being incorrectly transported from server to clients. I have a hunch that it might be the same root cause as with #747, but I have no proof. Since I cannot reproduce this on the latest release, I'm fairly convinced that this bug comes from our renaming of `game` to `match`. 

I would love to be able to create an integration test for this, but I cannot build the current 0.40 branch locally (see [the 0.40 PR](https://github.com/boardgameio/boardgame.io/pull/709#issuecomment-683666213)). Testing this requires having a server running, and multiple clients connecting, so it's a bit difficult to automate, but I see there's already an integration test in the code base so I was going to implement something similar. 

Once again, I'm happy to test this but I would like to have some help diagnosing the issue. :pleading_face:

**Comment by delucis** [comment]
Hey @adngdb I just tried this with 0.40.0, which has just been released, and couldn’t seem to reproduce it. I was able to create new matches and play with the expected result. Could you double check if you still see the bug after updating to 0.40.0?

**Comment by adngdb** [comment]
Release 0.40.0 solves this issue! Thanks a lot! :partying_face:
