### ISSUE TITLE
Page displaying "Not Found" and nothing else

### ISSUE THREAD

**Issue by JohnnyWobble** [boardgameio/boardgame.io#797]
I'm trying to write the `server.js` so I can deploy to Heroku, but the page just says "Not Found".

server.js
```js
import {Server} from 'boardgame.io/server'
import {Oversimplified} from "./game/game"
import path from 'path';
import serve from 'koa-static';

const server = Server({ games: [Oversimplified] });
const PORT = process.env.PORT || 8000;

// Build path relative to the server.js file
const frontEndAppBuildPath = path.resolve(__dirname, './build');
server.app.use(serve(frontEndAppBuildPath))

server.run(PORT, () => {
  server.app.use(
    async (ctx, next) => await serve(frontEndAppBuildPath)(
      Object.assign(ctx, { path: 'index.html' }),
      next
    )
  )
});
```

**Comment by delucis** [comment]
I’m not really familiar with Heroku, but do you need to specify somewhere how to build your page to the `'./build'` directory? You may have more luck getting some pointers over [in the boardgame.io Gitter chat](https://gitter.im/boardgame-io/General?source=orgpage) where I know some people have been using Heroku to deploy their games.

**Comment by Pong420** [comment]
You should check the build log of Heroku.
Have you add  the `start` scripts in  `package.json`?

**Comment by JohnnyWobble** [comment]
Yeah I added the start script and the build log is normal
```
2020-09-08T13:26:44.000000+00:00 app[api]: Build started by user 
2020-09-08T13:28:55.543540+00:00 app[api]: Release v11 created by user 
2020-09-08T13:28:55.543540+00:00 app[api]: Deploy a3e455ed by user
```

**Comment by Pong420** [comment]
Here is my server config. I am using `koa2-connect-history-api-fallback`
https://github.com/Pong420/boardgame/blob/e33ccc10fd1c64bed4641eaf0daca3e9cf2adc42/packages/server/src/index.ts#L63-L85

**Comment by JohnnyWobble** [comment]
Ok so I found my problem, it was using an old bugged build of my app. Once I rebuilt it, everything worked! Thanks for all your help though!
