### ISSUE TITLE
Can't run react-web examples

### ISSUE THREAD

**Issue by klrkt** [boardgameio/boardgame.io#798]
Hi

I cannot run react-web examples. 
There appears to be differences in the commits - that I do not understand.

This link offers some explanation: 
https://github.com/PJohannessen/four-in-a-row/commit/22c70ebc9709cf00dee15f7d310eb327b0f43744

Compare latest commit example with previous commit and you will note:
LATEST: react-web\src\random\index.js shows:  import { Client } from 'boardgame.io/client';
PREVIOUS: react-web\src\random\index.js shows:  import { Client } from 'boardgame.io/react';

Changing the 'random' example index.js to boardgame.io/react';  seems to work 
BUT CAUSES the 'threejs' example index.js to be unable to resolve dependency.

WINDOWS 10 Platform and nodejs install - all in last 45 days.

Hope you can help - thanks.

See my efforts below. 

### MY WINDOWS 10 COMMAND:   npm run build    RESULT: ISSUE: can't resolve dependency

 C:\a\react\boardgame\examples\react-web\src\random\index.js:10:23: Cannot resolve dependency 'boardgame.io/client'
   8 |
   9 | import React from 'react';
> 10 | import { Client } from 'boardgame.io/client';
     |                       ^
  11 | import Game from './game';
  12 | import Board from './board';
  13 |
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-web@ build: `parcel build src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-web@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bundy\AppData\Roaming\npm-cache\_logs\2020-09-08T21_29_16_384Z-debug.log

C:\a\react\boardgame\examples\react-web>npm run build

> react-web@ build C:\a\react\boardgame\examples\react-web
> parcel build src/index.html

×  C:\a\react\boardgame\examples\react-web\src\threejs\index.js:11:23: Cannot resolve dependency 'boardgame.io/client'
   9 | import React from 'react';
  10 | import * as THREE from 'three';
> 11 | import { Client } from 'boardgame.io/client';
     |                       ^
  12 | import TicTacToe from '../tic-tac-toe/game';
  13 | import './main.css';
  14 |
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-web@ build: `parcel build src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-web@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bundy\AppData\Roaming\npm-cache\_logs\2020-09-08T21_31_34_312Z-debug.log

C:\a\react\boardgame\examples\react-web>npm run build

> react-web@ build C:\a\react\boardgame\examples\react-web
> parcel build src/index.html

×  C:\a\react\boardgame\examples\react-web\src\threejs\index.js:11:23: Cannot resolve dependency 'boardgame.io/react'
   9 | import React from 'react';
  10 |
> 11 | import { Client } from 'boardgame.io/react';
     |                       ^
  12 | import * as THREE from 'three';
  13 | import TicTacToe from '../tic-tac-toe/game';
  14 | import './main.css';

**Comment by delucis** [comment]
Here are the steps to run the examples:

1. Clone the repository (which you’ve done)
2. Run `npm install` in the repository’s root directory
3. Run `npm start` in the repository’s root directory

It’s important to run these commands from the `boardgame.io` directory, not from the `examples` directory.

That said, it looks like you may also have an outdated copy of boardgame.io cloned. Could you double check the version number in `package.json`? You may want to pull the latest changes down then repeat steps 2 & 3 above and see if that helps.

**Comment by klrkt** [comment]
Thanks for the timely response.
For me, it is important to start with something that works.
I had done everything as per your steps 1,2,3 above - exactly as you wrote, which worked on Linux mint but failed when I moved to Windows 10.
THEN I tried npm install from the examples/react-web directory.
THEN I tried npm run build from the examples/react-web directory.
Just to be 100 percent sure - or as close as possible - I downloaded and tried the latest commit.
Again npm install failed - lots of "no such directory npm-modules/.Staging/[various npm modules])

After some trial and error - I think the failure appears to be a Windows 10 issue. I extracted the zip to my "Documents"  and tried - npm install, which failed - even when I tried npm install -force. (I ran from "CMD" - as Administrator.)

Frustrated - I tried again - to my surprise it worked.
My theory is that this time, coincidentally, windows was updating my system. 
I looked at this https://stackoverflow.com/questions/39293636/npm-err-error-eperm-operation-not-permitted-rename/51440223
"The problem is that in some cases, after the timeout, the file is still locked by the A/V. The solution is rip out the timeout and let this statement in loop. "
So it MAYBE that the update slowed npm install?

In any event I now have something that works - but which may be problematic to reproduce.

I again confirmed that the examples for "random" and "threejs" are inconsistent  "import { Client } from 'boardgame.io/react';" and "import { Client } from 'boardgame.io/client';" 

I am NOT obsessed - but I got into this problem of installing the examples because I had precisely the same problem when trying to follow the tutorial - PJohannessen/four-in-a-row@22c70eb (as mentioned above).

Can you offer any insight on:
1. Why are "random" and "threejs" examples coded differently?
2. How can I "strip" out the react-web example so that I can use it "stand alone"

Thanks, in advance, for your help and understanding.

klrkt

**Comment by delucis** [comment]
Glad you got it working — does indeed sound like it may have been a system/environment issue with Node.js/npm.

> 1. Why are "random" and "threejs" examples coded differently?

boardgame.io ships with two clients: one to use with React, and one that’s a plain JavaScript class that can be combined with any front-end framework/architecture. (And in fact, the React client is itself built on top of the “plain” client.)

The “random” example is built with React and so does `import { Client } from 'boardgame.io/react'`. The ThreeJS example doesn’t use React, so it does `import { Client } from 'boardgame.io/client'` to use the plain JavaScript client.

> 2. How can I "strip" out the react-web example so that I can use it "stand alone"

Have you read through [the official tutorial](https://boardgame.io/documentation/#/tutorial)? It covers both React & plain JS scenarios, using Tic-Tac-Toe as an example. I think the tutorial you link to may have been written with an older copy of boardgame.io and no longer be up-to-date.
