### ISSUE TITLE
Tutorial Client Broken (Plain-JS version)

### ISSUE THREAD

**Issue by jimu** [boardgameio/boardgame.io#804]
The "Plain JS" version of the [tutorial](https://boardgame.io/documentation/#/tutorial) crashes in Chrome v85.0.4183.102 running on Windows 10 Pro [1909 18363.778] with the message:

> Uncaught ReferenceError: regeneratorRuntime is not defined

This is a known issue and is documented here:

* Issue https://github.com/boardgameio/boardgame.io/issues/748 (Jun 19)
* [Gitter Sep 10 08:23](https://gitter.im/boardgame-io/General?at=5f5a28d5f969413294d7ea70)
* [Gitter Sep 20 21:35](https://gitter.im/boardgame-io/General?at=5f68118dc1d1a53705b63e3c)

There are three solutions/workarounds that solve the problem:

1. Modify `package.json`
> If you’re following the plain JS tutorial, you can explicitly declare that you don’t want to support old browsers with a browserslist field in package.json:
> 
> `"browserslist": "> 0.4% and not ie 11"`

2. Import regenerator package in App.js:
> Added import 'regenerator-runtime/runtime' to the start ot src/App.js.

3. Use Webpack instead of Parcel
[Tutorial amended with Webpack steps](https://osaka.jimu.net/bgio/#/tutorial)

Please show compassion towards frustrated new users by updating the tutorial with one or more of these fixes

**Comment by delucis** [comment]
Thanks for collating these three fixes! I think Webpack may introduce more complexity than is desirable for an introductory tutorial, but perhaps we could add a note about one of the other two options. I would perhaps lean towards the `browserslist` option.

If you fancy writing a blog post about getting boardgame.io up and running with Webpack, I'm sure that could be helpful to some users too!

**Comment by jimu** [comment]
`browserlist` seems like the most reasonable solution to me as well. Thanks

**Comment by nicolodavis** [comment]
Thanks for bringing this to our attention @jimu. I also concur with the `browserlist` solution.

**Comment by joeynator2000** [comment]
This does nothing for me. I did the tutorial step by step 10 times and out of these attempts 1 worked. I cannot even get a new version of the same tutorial to work. When following the tutorial to npm strat and it says I should see the  Debug Panel does simply not happen. Where would my mistake be? The browser list is always yellow saying incompatible type.

**Comment by delucis** [comment]
Just a quick note to anyone finding this issue in the future, the `browserslist` query documented here is outdated. See [the tutorial](https://boardgame.io/documentation/#/tutorial) for the updated version.
