### ISSUE TITLE
playerView executed twice for multiplayer game

### ISSUE THREAD

**Issue by larry801** [boardgameio/boardgame.io#818]
When using playerView to calculate results from secret info, boardgame.io crashes.

Here is a minimal reproduce.
https://codesandbox.io/s/boardgameio-typescript-player-view-issue-demo-f-hefjq?file=/src/Game.ts

**Comment by delucis** [comment]
Thanks! It should be possible to only run `playerView` on the client if it isn’t a multiplayer client by moving it behind a `!this.multiplayer` check here:

https://github.com/boardgameio/boardgame.io/blob/6b6b175636216c4c30b52d6d9809c4e938511431/src/client/client.ts#L438
