### ISSUE TITLE
Project is not buildable 

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#822]
I tried to build project locally after merge with PR ( https://github.com/boardgameio/boardgame.io/pull/691) to finally close this PR. However i noticed problems with `WrappedBoard` type. 
When i run build `npm run-script build` it throws : 
```[!] (plugin rpt2) Error: /Users/grzegorz/Projects/boardgame.io/src/client/react.tsx(135,59): semantic error TS2339: Property 'forceUpdate' does not exist on type 'WrappedBoard'.```
And when i go to `src/client/react.tsx` its full of error related to `WrappedBoard`.

**Comment by delucis** [comment]
Have you run `npm install` after the merge? Sounds like it might be an issue with using an outdated version of some types package.

**Comment by pociej** [comment]
@delucis sorry for disturbing, you are obviously right.
