### ISSUE TITLE
Question about storing game assets

### ISSUE THREAD

**Issue by trung2012** [boardgameio/boardgame.io#824]
Hello,

Noob here. I have gone through the docs but could not find any information on how to store game assets in a database. The server and implemented storage options seem to only sync the game state. For example, if I'm building a card game and have the card objects, should I just keep them in the client code? If I want to store the card objects in a database and just retrieve them when the game loads to reduce the client bundle size, is it possible? (I don't want to manually add card objects when I need to add expansions either)

Thanks!

**Comment by larry801** [comment]
Your issue title is a bit confusing ,the term "game assets" usually refers to media files like pictures, 3D models or sound, which should not be put into database. If you want to reduce client bundle size just put them on a CDN or storage services on the cloud. According to issue content you may what to store card properties (like name cost  effects etc.) in a database. If so here are several ways.

- Put card objects in Cloud Object Storage and retrieve with its REST API on client
- Retrieve directly using node connector of your database of choice
- roll your own  [storage adapter](https://boardgame.io/documentation/#/storage?id=writing-a-custom-adapter) and add the card objects retrieving there.

**Comment by larry801** [comment]
Reducing bundle size by stripping card data can be a kind of premature optimization. boardgame.io it self takes up about 40KB after gzipped and minified, All code including card data and logic of a card game I am implementing takes up 40KB.card data only consists of 10KB .
Unless your game have thousands of cards, splitting can make things worse.
You can also try React.Lazy to achieve a similar effect.

**Comment by trung2012** [comment]
Thank you for the answer! I was actually just asking about the card properties but did not phrase it well enough. I was thinking maybe later on to implement multiple expansions but I guess even with expansions there won't be thousands of cards. I will just keep it in the client code until problems show up.
