### ISSUE TITLE
Release v0.41.1 of boardgame.io broke the usage of bgio-storage-cache

### ISSUE THREAD

**Issue by evandroabukamel** [boardgameio/boardgame.io#830]
I'm just testing some stuff with the new release of boardgame.io and I noticed an error on match creation by bgio-storage-cache.
This is related with the change I worked on about game/match consistency. My fault, I forgot about this lib.

Should have to create the deprecated methods on the derived classes too, Flatfile and InMemory?

```
Using the deprecated createGame method instead.

  TypeError: this.db.createGame is not a function
      at StorageCache.<anonymous> (./node_modules/bgio-storage-cache/dist/bgio-storage-cache.js:69:27)
```

**Comment by delucis** [comment]
Yes, patching this in the derived classes while the methods are deprecated rather than removed seems like it might be a good idea. Something like:

```ts
class Impl extends Async {
  // ...

  /**
   * @deprecated Use createMatch instead.
   */
  createGame(matchID: string, opts: CreateMatchOpts) {
    return this.createMatch(matchID, opts);
  }
}
```

**Comment by delucis** [comment]
@evandroabukamel Actually, after consideration, I think this should be fixed in https://github.com/delucis/bgio-storage-cache/issues/3 — `FlatFile` and `InMemory` only need to be compatible with the current version of boardgame.io. The storage cache special case should be updated there.

**Comment by evandroabukamel** [comment]
Alright, thanks.
