### ISSUE TITLE
Infinite recursion on `hasBinary` when sending moves from client to server

### ISSUE THREAD

**Issue by simlmx** [boardgameio/boardgame.io#833]
It took me a few hours to find the solution to this problem so I figured I would share it here.

Basically I have a React game and got the following error when the client is trying to send its move to the remote server using `SocketIO`:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at hasBinary (index.js:44)
    at hasBinary (index.js:59)
    at hasBinary (index.js:59)
    at hasBinary (index.js:59)
   ...
```

So what happened is that I had a `<button>` inside a React component making a move like this:
```javascript
<button onClick={ this.props.moves.someMove }> 
   Do the move!
</button>
```

I'm no React expert but, IIUC, this meant that the button itself was sent to the server, and it probably contains some circular references, hence the infinite recursion.

The solution was simply to change it to
```javascript
<button onClick={ () => this.props.moves.someMove() }> 
   Do the move!
</button>
```

**Comment by aherriot** [comment]
Thank you for this post. I ran into the exact same issue. It works in client-side only but fails when you change to a multiplayer configuration using SocketIO.
