### ISSUE TITLE
Keep track of players' connection status

### ISSUE THREAD

**Issue by pastDexter** [boardgameio/boardgame.io#834]
It would be useful to keep track of all players' connections status and broadcast that info to other players. This would allow displaying connection status next to player info and let other players know that they are currently unavailable due to e.g. network issues.

I think the best place to store that info is `matchData` 
```
[
  { id: 0, name: 'Alice', isConnected: true },
  { id: 1, name: 'Bob', isConnected: false }
]
```

It could use server-side SocketIO connect/disconnect events to modify `matchData` and broadcast that info independently of game state.

If you think it's a nice-to-have feature in the framework I'd be happy to work on it and prepare a PR.

**Comment by delucis** [comment]
Sounds nice! A PR would definitely be welcome.
