### ISSUE TITLE
Start boardgame.io server error on Mac

### ISSUE THREAD

**Issue by VjGusev** [boardgameio/boardgame.io#844]
Try to start server on Mac, as in [tutorial](https://boardgame.io/documentation/#/tutorial): `node -r esm src/server.js`
And get such error: 
```
/Users/gus/Documents/TUD_PhD/maths-duel-react-2/node_modules/boardgame.io/dist/cjs/server.js:1
TypeError: Cannot read property 'processMove' of undefined
    at IsProcessed (/Users/gus/Documents/TUD_PhD/maths-duel-react-2/node_modules/boardgame.io/dist/cjs/server.js:1605:17)
    at ProcessGameConfig (/Users/gus/Documents/TUD_PhD/maths-duel-react-2/node_modules/boardgame.io/dist/cjs/server.js:1624:9)
    at Array.map (<anonymous>)
    at Server (/Users/gus/Documents/TUD_PhD/maths-duel-react-2/node_modules/boardgame.io/dist/cjs/server.js:3250:19)
    at Object.<anonymous> (/Users/gus/Documents/TUD_PhD/maths-duel-react-2/src/server.js:5:16)
    at Generator.next (<anonymous>)
```

I have tried the solutions from this [chat](https://gitter.im/boardgame-io/General?source=orgpage), but they doesn't work for me.

**Comment by delucis** [comment]
Could you share the code in `src/server.js`?

This error looks like you’re passing an undefined game object in your server setup.

**Comment by VjGusev** [comment]
> Could you share the code in `src/server.js`?
> 
> This error looks like you’re passing an undefined game object in your server setup.

```
const { Server } = require('boardgame.io/server');
const { MathDuels } = require('./Game.js');

const server = Server({ games: [MathDuels] });

server.run(8000);
```

**Comment by delucis** [comment]
Try logging `MathDuels` to check you’re importing the game object you expect:

```diff
const { Server } = require('boardgame.io/server');
const { MathDuels } = require('./Game.js');
+ console.log('My game object is', MathDuels);

const server = Server({ games: [MathDuels] });

server.run(8000);
```

**Comment by VjGusev** [comment]
> Try logging `MathDuels` to check you’re importing the game object you expect:
> 
> ```diff
> const { Server } = require('boardgame.io/server');
> const { MathDuels } = require('./Game.js');
> + console.log('My game object is', MathDuels);
> 
> const server = Server({ games: [MathDuels] });
> 
> server.run(8000);
> ```

It was undefined, I've fixed it. Thanks very much.
