### ISSUE TITLE
lobbyClient.createGame is returning "Game TicTacToe not found"

### ISSUE THREAD

**Issue by officialcliffman** [boardgameio/boardgame.io#850]
When trying to create the Match in App.js as follows, it will return in the logs "Game TicTacToe not found":

`const res = lobbyClient.createMatch("TicTacToe", {
            numPlayers: 2,
})`

Server:
`
const server = Server({ games: [TicTacToe],
    db: new FlatFile({
        dir: '/storage/directory',
        logging: (true),
      }), });`

`lobbyClient.listAll` returns an array with only one value which is 'default' and no errors, so I assume that the server is setup correctly. 
Does anyone have any ideas? I've been struggling to debug from my end.

**Comment by delucis** [comment]
Have you set `name` on your game? For the above to work, the `TicTacToe` game object would need to look like:

```js
const TicTacToe = {
  name: 'TicTacToe',
  // setup, moves, etc.
};
```

If `name` isn’t set, it automatically gets set to `'default'`, so creating a match would look like:

```js
const res = await lobbyClient.createMatch('default', { numPlayers: 2, });
```

**Comment by officialcliffman** [comment]
Thank you so much. Worked perfectly.
