### ISSUE TITLE
Dispatch custom websocket events from client

### ISSUE THREAD

**Issue by julesbou** [boardgameio/boardgame.io#851]
I'm looking for a way to add rematch functionality.  I want to offer the possibility, at the end of a match, to play a new one with the same player. I know this is not possible actually, but I'm looking for proper way to do it using custom events/plugins.

The basic concept is:

- At the end of a game, one of the players can offer the other to rematch.
- The other player then receive a message asking him if he accept the rematch.

I'm looking for a way to communicate between both clients (in multiplayer mode) using websockets. I spend quite a lot of time playing with the transport/socket on the client trying to achieve that, without success.

What is the recommended way to send a websocket event from one client to another?

**Comment by delucis** [comment]
@julesbou Have you checked out the [`playAgain` lobby API endpoint](https://boardgame.io/documentation/#/api/Lobby?id=playing-again)?

**Comment by julesbou** [comment]
`/playerAgain` lobby API endpoint doesn't makes a lot of sense in multiplayer IMHO. Unless we want to automatically play with the same opponent after each match. But that's not the case in the vast majority of games. In most game we would ask "do you want to play again with same person?" and "do you want to play with a new person?" That endpoint totally misses that fact.

I just want to send a message from one client to an other. I tried `[updatePlayer()](https://boardgame.io/documentation/#/api/Lobby?id=updating-a-players-metadata)`, but it doesn't seems to work, sending `data` parameter has no effect.
