### ISSUE TITLE
Running Examples

### ISSUE THREAD

**Issue by dondragon2** [boardgameio/boardgame.io#864]
I have checked out the repo and followed the instructions to get the server running but I am not able to access anything.

if I go to `http://localhost:8000` I get a not found error. If I go to `http://localhost:3000/lobby/main` nothing happens. I saw the following error in the console also.

![image](https://user-images.githubusercontent.com/3165843/101849445-4bfe9d00-3b1d-11eb-8bbe-7fc2aaddf17e.png)

**Comment by delucis** [comment]
@dondragon2 Thanks for the issue report. I was able to reproduce this and 2cc6104 should fix it — try fetching and re-running `npm install; npm start`.
