### ISSUE TITLE
Move Type: Need "MoveFn" alone instead of "MoveFn | LongFormMove"

### ISSUE THREAD

**Issue by jakehsiao** [boardgameio/boardgame.io#867]
Because everytime I call another move as a function in a move, the typescript says that "Not all "Move" is callable".

But I cannot import "MoveFn" alone and can only import the whole "Move" type.

Are there any methods to extract the "MoveFn" type out?

**Comment by delucis** [comment]
Hi @jakehsiao — we can probably export `MoveFn` directly [from `src/types.ts`](https://github.com/boardgameio/boardgame.io/blob/3918cc901099c52079c4ff95c6768446e8f52409/src/types.ts#L143). Want to open a PR?

**Comment by jakehsiao** [comment]
@delucis Yeah, of course it's the simplest method. And maybe it's good to export more types to make it more flexible with typescript.
However, are there any other ways can achieve this without changing the codebase? I am not that familiar with typescript so I wonder whether there are some pure typescript ways to extract one type out of an union type, like extract "MoveFn" from "MoveFn | LongFormMove".

**Comment by delucis** [comment]
It might well be possible to write a generic that extracts it. (On my phone so haven't tested this.)

```ts
type ExtractFn<T extends any> =
  T extends (...args: any[]) => any ? T : never;

type MoveFn = ExtractFn<Move>;
```

Otherwise I'd need to see a code sample. You might be able to avoid using the `Move` type completely, but I think that usually requires you to specify `G` and `ctx` types for each function.
