### ISSUE TITLE
What is the type of "props.moves" in react client's board

### ISSUE THREAD

**Issue by jakehsiao** [boardgameio/boardgame.io#869]
I know the type of "props.G" is defined by the project, and "props.ctx" is "Ctx", but what is the type of "props.moves"?

`
export function Board(props: {G: IGame, ctx: Ctx, moves: any}) {
 ...
}
`

Currently I am using "any" but this is not a safe way at all.

Also, it's quite appreciated to add some examples and documentations on using boardgame.io with typescript.

**Comment by delucis** [comment]
[Here's a small example using Typescript](https://codesandbox.io/s/boardgameio-typescript-demo-u5uvm), but yes proper TS documentation is still needed.

We don't have strongly typed moves, although it might be theoretically possible to compute them from a game definition, so for now `moves` is

```ts
type moves = Record<
  string,
  (...args: any[]) => void
>;
```

If you follow the example linked above though you shouldn't have to type this manually. If you specifically need the moves type you can use `BoardProps['moves']`.

**Comment by jakehsiao** [comment]
@delucis Thanks, this demo is quite helpful. Maybe it's impossible for typescript now to give a 100% type check.

**Comment by delucis** [comment]
@jakehsiao It’s tricky. If you declare your game as `const game = { ... } as const`, in theory Typescript can read all the moves keys and iterate over them to produce the type of `props.moves` ([here’s an experimental implementation][impl]). However, then you have to type everything in the game definition manually. If you use the `Game` type (or other types like `Move`), like `const game: Game = { ... }`, then Typescript can’t parse specific moves any more as it just sees the generic `Game` type.

I’m not sure the trade-off of typing everything manually is worth it, even though having auto-completion and type safety on the client would be nice.

[impl]: https://github.com/boardgameio/boardgame.io/pull/801#pullrequestreview-487295970
