### ISSUE TITLE
How to use server with typescript

### ISSUE THREAD

**Issue by jakehsiao** [boardgameio/boardgame.io#874]
The documentation on server is only about js.

First I just copied the code in documentation into "server.js", but it failed because games are defined in typescript and js cannot import typescript modules.

Then I change it to "server.ts", but now I don't know how to run this.

So how to use server with typescript?

**Comment by larry801** [comment]
You need to build typescript first. Please refer to this project for more
detail.
https://github.com/averycrespi/thinktank

https://github.com/averycrespi/thinktank/blob/f72fd089edaf5bc04b6600995065589a383c4703/package.json#L44

**Comment by delucis** [comment]
As @larry801 says, you need to compile the `.ts` file to plain JavaScript before running it with Node.

One other option is to use something like [`ts-node`](https://www.npmjs.com/package/ts-node), which allows you to transpile and run from a single command (like `ts-node ./server.ts`). There are some limitations with ES modules, so you may need to tweak `tsconfig.json` to get this working correctly.
