### ISSUE TITLE
Authenticate chat messages

### ISSUE THREAD

**Issue by delucis** [boardgameio/boardgame.io#876]
I didn’t have time to look at #871 before it was merged, but I see now it didn’t include authentication like we now have for all the other game master methods (partly because #853 was only merged after @TomasVidhall started work).

Should we use player credentials for authentication? This would only allow players rather than spectators to chat, but currently an unauthenticated client could post a message claiming to be an authenticated player.

**Comment by nicolodavis** [comment]
Good call! Sorry I missed that earlier.

**Comment by nicolodavis** [comment]
@TomasVidhall Would you have time to expand on your original PR?

**Comment by TomasVidhall** [comment]
I can take a look after Christmas 🎄
