### ISSUE TITLE
Server cannot synchronize functions defined in G to Client

### ISSUE THREAD

**Issue by jakehsiao** [boardgameio/boardgame.io#883]
This causes plenty of bugs where do not exist when played at local but exist when played in multiplayer mode with server.

I tried the following definition:
`
const G = {
  f1: () => "f1",
  f2: () => "f2",
}
`

And a move:
`
console.log("F1:", G.f1);
console.log("F2:", G.f2);
`

In server, the functions are well defined:
![image](https://user-images.githubusercontent.com/16620878/103443784-6dc2ee00-4c9d-11eb-9f01-c8f44155e8e8.png)

But in client, the functions are not passed from server:
![image](https://user-images.githubusercontent.com/16620878/103443799-87fccc00-4c9d-11eb-9996-e654de0eec5d.png)

However in local mode, the functions work again:
![image](https://user-images.githubusercontent.com/16620878/103443821-a95db800-4c9d-11eb-8674-beae5562d85a.png)

**Comment by delucis** [comment]
This is expected behaviour — there’s no safe way to serialize functions to send back and forth across the network. As it says [in the docs](https://boardgame.io/documentation/#/?id=state):

> Because state can be sent between client and server, `G` must be a JSON-serializable object; in particular, it must not contain classes or functions.
