### ISSUE TITLE
Update Match ID and Match Unlisted using React Client

### ISSUE THREAD

**Issue by iCrashed** [boardgameio/boardgame.io#897]
I can't find a way to update match Id and also update match unlisted attribute to true. 

According to [this document](https://github.com/boardgameio/boardgame.io/blob/master/docs/documentation/api/Client.md)  we can update the matchID in Plain JS Client with 
 
 `updateMatchID(id) `
 
How can I achieve this with React client?

**Comment by delucis** [comment]
Using a React client you can set the `matchID` to connect to by passing it as a prop:

```js 
<Client matchID="my-match-id" />
```

If the prop changes, the client will reload and use the new `matchID`.

`unlisted` is an option when creating a match using the Lobby API, so you can’t set it directly on a client, instead you have to send it as part of the create match request.

**Comment by binish784** [comment]
Facing the same issue, how can we unlist a match after match creation, lets say like once the number of players connected to a match is full ?

**Comment by iCrashed** [comment]
So how do I stop the match from being listed after all the players have joined the lobby? Do you know how others are handling this case?

**Comment by delucis** [comment]
Ah, there’s no way to change `unlisted` currently. Are you trying to only display matches with open spaces? If you’re looking for a way to do that, I would do something like this on the client:

```js
const hasEmptySeat = (match) => match.players.some(player => !player.name);
const openMatches = matches.filter(hasEmptySeat);
```

`unlisted` was intended mainly to allow clients to create a match that is _never_ listed. The create endpoint returns a `matchID`, so you can then do something like share a URL with that ID so only friends have access to the match.

Assuming you are trying to only list open matches, what might make more sense would be to extend the match listing functionality, so it would be possible to request only matches that aren’t full (similar to what #740 implemented for time and gameover queries).
