### ISSUE TITLE
missing documentation for chat 

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#911]
I think title is self-explaining.

**Comment by Dissolutio** [comment]
Howdy y'all, first time contributor here. I did this, made a Chat Guide page. It offers and links to the same information that is on the Client API page. I added a warning about chats not being received until connected. 

Do I open a pull request? Open to discuss and make changes.

Some ideas
- add to homepage, mentioning Chat somewhere in the feature list?
- add warning about needing to generate your own unique id's for chats?
- do we want code sandbox examples on the page?

Thanks!

**Comment by delucis** [comment]
@Dissolutio A PR would be perfect! Let’s start with what you’ve got so far and go from there.
