### ISSUE TITLE
Array in G not updating except by explicit indexing

### ISSUE THREAD

**Issue by Pilipo** [boardgameio/boardgame.io#913]
I am keenly aware that this is likely user error, but I'm pulling hair out and don't know who else to ask about this.

I have an array like the tictactoe example:
```Javascript
{
  cells: Array(651).fill(tileProperties),
}
```
When I try to access and manipulate a cell parameter using a calculated index, it fails to update the cell parameter. However, if I address the cell by hardcoding the intended index, it works.

### This doesn't work
```Javascript
    const originIndex = TileHelper.tileCoordinatesToIndex({ x: this.x, y: this.y });
    console.log(originIndex) // returns 147
    G.cells[originIndex].occupied = false;
    // G.cells[147].occupied = false;
```
### This does work
```Javascript
    const originIndex = TileHelper.tileCoordinatesToIndex({ x: this.x, y: this.y });
    console.log(originIndex) //returns 147
    // G.cells[originIndex].occupied = false;
    G.cells[147].occupied = false;
```
Is this an issue with me going too far against the immutability pattern? Is this the totally wrong place to put the question? (if so, please for give me) Thanks for any help you can offer.

PS - When I address the array by calculated index, I can console the result and confirm that it works _locally_, but out at the Game object `G` returns an unexpected `true` value.

**Comment by delucis** [comment]
@Pilipo From what you’ve shared, I don’t think it’s an immutability problem, but I have a couple of questions:

1. What is `this` in your code snippets? Moves and other code shouldn’t refer to state outside the function body, so I’m curious about the full context for this code.

2. When you write 

    > the Game object `G` returns an unexpected `true` value.

    Do you mean that `console.log(G)` prints `true` rather than your state? If so, I would expect `G.cells[idx]` to actually error, so perhaps you mean something else.

**Comment by Pilipo** [comment]
@delucis Thanks for your questions.

1. In my game I have game tokens called Clones that are represented by a class (included below). When a Clone is placed on the board, I track this by instantiating a Clone object that has a `move()` method. I pass the `G` of game into that method call to update the properties on the cell the Clone moves from and the cell it moves to. This is how I am determining whether the cell is occupied so that other Clone movement can be determined. 
```Javascript
// rough idea of a Clone's location in G
{
  ...
  cells: [
    {cell stuff},
    {cell stuff},
    {cell stuff},
    ...
  ],
  players: [
    {
      clones: [
        <Clone>,
        <Clone>,
        <Clone>,
      ],
    },
    {
      clones: [
        <Clone>,
        <Clone>,
        <Clone>,
      ],
    },
  ],
  ...
}
```
```Javascript
class Clone {
  constructor(playerID, coordinates) {
    this.x = coordinates.x;
    this.y = coordinates.y;
    this.spy = false;
    this.gunner = false;
  }

  move(G, ctx, tarCoords) {
    const originIndex = TileHelper.tileCoordinatesToIndex({ x: this.x, y: this.y });
    const tarIndex = TileHelper.tileCoordinatesToIndex({ x: tarCoords.x, y: tarCoords.y });
    if (JSON.stringify(originIndex) === JSON.stringify(tarIndex)) {
      return;
    }
    console.log(` this is origin ${originIndex}`);
    // console.log(`BEFORE: origin cell ${originIndex} occupied? ${G.cells[originIndex].occupied}`);
    G.cells[originIndex].occupied = false;
    // G.cells[147].occupied = !G.cells[originIndex].occupied;
    // console.log(`AFTER: origin cell ${originIndex} occupied? ${G.cells[originIndex].occupied}`);

    // console.log(`BEFORE: target cell ${tarIndex} occupied? ${G.cells[tarIndex].occupied}`);
    // G.cells[tarIndex].occupied = true;
    // console.log(`AFTER: target cell ${tarIndex} occupied? ${G.cells[tarIndex].occupied}`);

    this.x = tarCoords.x;
    this.y = tarCoords.y;
  }
}
```
2. I was unclear in my description here. What I meant was that in the `Clone.move()` method once I have set `G.cells[originIndex].occupied = false;` I can do `console.log(G.cells[originIndex].occupied)` and it prints `false`. However, out in the Game object, where `Clone.move()` is originally called, when I do `console.log(G.cells[147].occupied)` I get `true` as if the set never happened. As I mentioned in the original question, though, if I set the parameter inside `Clone.move()` like this `G.cells[147].occupied = false;` (instead of calculating the index) it all works fine and a `console.log(G.cells[147].occupied)` out in `G` prints `false` as I would expect.

**Comment by delucis** [comment]
Ah, OK! So you can’t have class instances inside `G` (see [the red comment in the docs here](https://boardgame.io/documentation/#/?id=state)). Not clear if when you said “it works _locally_” you meant this issue was showing up with a server, but when we do something like `JSON.stringify({ clone: <Clone> })` to send data to the client, `clone` will be removed because it is not serializable to JSON. (We actually _just_ merged [a commit](01c522cf17a406a7dc109260be20ed910061503a) to warn about this, but haven’t released it yet.)

Would I be right in thinking your moves look something like this?

```js
const game = {
  moves: {
    addClone: (G, ctx, coordinates) => {
      const clone = new Clone(ctx.playerID, coordinates);
      G.players[ctx.playerID].push(clone);
    },
    moveClone: (G, ctx, cloneIndex, tarCoords) => {
      const clone = G.players[ctx.playerID][cloneIndex];
      clone.move(G, ctx, tarCoords);
    },
  }
};
```

Because we can’t serialize classes you probably need to refactor this to separate the class properties from the class methods:

```js
// Create an object with the clone’s data
const createClone = ({ x, y }) => ({ x, y, spy: false, gunner: false });

// Function that mutates a clone object
const moveClone = (G, ctx, clone, tarCoords) => {
  // your various logic then mutate the clone
  clone.x = tarCoords.x;
  clone.y = tarCoords.y;
}

const game = {
  moves: {
    addClone: (G, ctx, coordinates) => {
      const clone = createClone(coordinates);
      G.players[ctx.playerID].push(clone);
    },
    moveClone: (G, ctx, cloneIndex, tarCoords) => {
      const clone = G.players[ctx.playerID][cloneIndex];
      moveClone(G, ctx, clone, tarCoords);
    },
  }
};
```

**Comment by Pilipo** [comment]
Your guess at my move approach is almost exactly right, yes. 

One added complexity (again probably my lack of understanding) is that the client is only sending one move, which is `clickCell(idx)`. I'm using a switch case on turn stage to determine whether to place a clone, move a clone, fire a weapon, etc. Your direction to refactor is still appropriate, of course, but my approach will likely differ from adding moves for `addClone()` and `moveClone()`.

This has been extremely helpful. Thank you for looking at this.

**Comment by delucis** [comment]
Great! I’m closing this as I think we’ve reached an answer (if indirectly). Feel free to ask any more questions though if you have them.
