### ISSUE TITLE
boardgames.io website is unreachable

### ISSUE THREAD

**Issue by foush** [boardgameio/boardgame.io#914]
When attempting to open the docs referenced on the readme, I get a chrome "unsafe connection" message. If I attempt to proceed anyway, I am immediately redirected to a malware site

**Comment by delucis** [comment]
Curious — I can’t reproduce that (tried in Chrome 88 and Firefox 85). Are you still seeing this? Would you be able to do some digging to understand what might be causing this?

**Comment by foush** [comment]
I apologize, it seems to be a problem on my end. If I go to the site on my phone with wifi off it resolves fine. When I turn wifi on, the message appears. Closing.
