### ISSUE TITLE
Storage interface. 

### ISSUE THREAD

**Issue by pociej** [boardgameio/boardgame.io#921]
I'm going to implement mongo connector. I went through existing implementation for postgress and azure. I found the quite messy. Tell me if im wrong, I don't like ts so im not expert in it and i can be wrong but... If decision is made and we have typescript,  why not to make use of it?  Shouldnt bgio export `StorageInterface` and only job for connector to given db would be to implement this interface ?

**Comment by larry801** [comment]
It is quite clear in documentation.
https://boardgame.io/documentation/#/storage?id=writing-a-custom-adapter
Create a class that implements the StorageAPI.Async
<https://github.com/boardgameio/boardgame.io/blob/master/src/server/db/base.ts>
 interface.

**Comment by delucis** [comment]
We already export these abstract classes as @larry801 mentioned. (In fact, @pociej [you added the export for `Sync`](144de643efdf1de6b67828d0fb282b623ec633cd) 😄.)

```js
import { Async } from 'boardgame.io/internal';

class MyStorage extends Async {
  // implement methods
}
```

A few of the return types are a little fiddly, but with any luck the other implementations should make their usage clearer. Here’s [my Firestore storage implementation](https://github.com/delucis/bgio-firebase/blob/latest/src/firestore.ts) for reference too.

I’ll close this as I think the request (to export the interface) is already available. Please let me know if I’ve misunderstood.

**Comment by pociej** [comment]
>  (In fact, @pociej [you added the export for `Sync`] 

ROTFL
