### ISSUE TITLE
Exporting more types & interfaces

### ISSUE THREAD

**Issue by SaFrMo** [boardgameio/boardgame.io#926]
I'd like to use the `PhaseMap` type in my project but am running into this error when trying to import: `Module '"boardgame.io"' declares 'PhaseMap' locally, but it is not exported.ts(2459)`

Is there some other way I should be doing this? I'm looking to define the `phases` property for a `Game` object and it looks like PhaseMap should be the way to go, but I can switch to something else if needed.

I looked in the types file and found a couple more that weren't exported, so I put together a quick branch [here](https://github.com/boardgameio/boardgame.io/compare/master...SaFrMo:safrmo/type-exports) to resolve. Happy to submit a PR if this is a useful addition. Thanks for the excellent work!

**Comment by delucis** [comment]
@SaFrMo Sure! A PR for this would be good.

**Comment by delucis** [comment]
Closed in #927
