### ISSUE TITLE
ctx should include stage

### ISSUE THREAD

**Issue by JoeLudwig** [boardgameio/boardgame.io#933]
It is convenient and straightforward to use the phase in the ctx object to determine what UI to show on the client. It would be good to be able to use the same sort of check for the current stage. Instead the game has to store something in G that clues the UI into the fact that a particular stage is active.

Or at least I haven't found stage in the object:
![image](https://user-images.githubusercontent.com/303656/115999532-ffce6980-a5a0-11eb-9bce-7f3c3d17d0c2.png)

It's definitely not in the typescript declaration for Ctx.

**Comment by JoeLudwig** [comment]
Then I looked at my own screenshot and saw it under activePlayers. I guess that's the stage of each active player?

**Comment by delucis** [comment]
@JoeLudwig Yup, exactly. Each player could be in a different stage so stages are stored in the `activePlayers` map, keyed by the player ID. If no player is in a stage, `activePlayers` is `null`.
