### ISSUE TITLE
Feature Request - Allow to specify next phase using a function

### ISSUE THREAD

**Issue by johwic** [boardgameio/boardgame.io#954]
**Problem:** Currently the `next` field in the phase configuration only accepts a string.

 I'm trying to write a phase using the `TurnOrder.ONCE` turn order, however the next phase needs to be determined dynamically. The only way to do this as far as I know is to specify an `endIf` function, but this clashes with automatic phase-ending `TurnOrder.ONCE`. I could write such a function, but especially since `endIf` is called before the phase is even begun, in my case the logic to accomplish this gets unnecesarily convoluted. It would be convenient if the `next` field accepted a function to allow to determine the next phase dynamically, without interfering with phase-ending logic.

**Comment by delucis** [comment]
Sounds like a good idea!

You _could_ use the default turn order with an `endIf` that returns `{ next }`, but as you mention that can easily require extra logic and we could support this more cleanly using your suggested approach.
